name: Build Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - windows-2025

    steps:
      - run: |
          vcpkg install \
            boost-program-options:x64-windows \
            bzip2:x64-windows \
            expat:x64-windows \
            lz4:x64-windows \
            nlohmann-json:x64-windows \
            zlib:x64-windows
        shell: bash

      - uses: actions/checkout@v6

      - uses: ./.github/actions/install-from-git

      - uses: ./.github/actions/cmake-windows

      - uses: ./.github/actions/build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osmium-tool-windows-${{ matrix.os }}
          path: build/src/Release/
