name: Build Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install vcpkg dependencies
        run: |
          vcpkg install `
            boost-program-options:x64-windows `
            bzip2:x64-windows `
            expat:x64-windows `
            lz4:x64-windows `
            nlohmann-json:x64-windows `
            zlib:x64-windows
        shell: bash

      - uses: ./.github/actions/install-from-git

      - uses: ./.github/actions/cmake-windows

      - uses: ./.github/actions/build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osmium-tool-windows
          path: build/Release/
